name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ github.repository_owner }}   # Pre-defined variable by GitHub Actions
          password: ${{ secrets.GITHUB_TOKEN }}      # Pre-defined

      - name: Echo Hello
        env: 
          GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
        run: echo $GITHUB_RUN_NUMBER
      
